Update launch-task

diff --git a/launch-task b/launch-task
--- a/launch-task
+++ b/launch-task
@@ -15,21 +15,32 @@ if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
     echo "⚠️ AWS_DEFAULT_REGION is not defined, so aws cli might not work"
 fi
 
-if [[ $# -le 1 ]] ; then
-    echo '❌ At least 2 argument are required: <cluster_name> <command>'
-    echo 'launch-task <cluster_name> <command>'
+if [[ $# -le 2 ]] ; then
+    echo '❌ At least 3 argument are required: <cluster_name> <command>'
+    echo 'launch-task <cluster_name> <task_name> <command>'
     exit 1
 fi
 
-CLUSTER_NAME="${1}"
-CMD_ARGUMENT="\"${@:2}\""
+if ! [ -x "$(command -v ecs-cli)" ]; then
+  echo '❌ Error: ecs-cli is not installed.'
+  echo 'ℹ️  Install in MacOS: brew install amazon-ecs-cli'
+  echo 'or more information in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html'
+  exit 1
+fi
 
-CONTAINER_NAME=$CLUSTER_NAME
+## Setup ENV Vars
+## --------
+
+CLUSTER_NAME="${1}"
+SERVICE_NAME="${2}"
+CMD_ARGUMENT="\"${@:3}\""
+
+CONTAINER_NAME=main
 
 ## Get network variables
 ## --------
 
-readonly ECS_CLUSTER_DATA="$(aws ecs describe-services --cluster ${CLUSTER_NAME} --services ${CLUSTER_NAME})" 
+readonly ECS_CLUSTER_DATA="$(aws ecs describe-services --cluster ${CLUSTER_NAME} --services ${SERVICE_NAME})" 
 readonly ECS_SUBNETS=$(echo $ECS_CLUSTER_DATA | jq -r '.services[].networkConfiguration.awsvpcConfiguration.subnets[]')
 readonly ECS_SECURITY_GROUPS=$(echo $ECS_CLUSTER_DATA | jq -r '.services[].networkConfiguration.awsvpcConfiguration.securityGroups[]')
 
@@ -38,10 +49,13 @@ if [ -z "${ECS_SUBNETS}" ] || [ -z "${ECS_SECURITY_GROUPS}" ]; then
     exit 1
 fi
 
+echo "ℹ️ Cluster: ${CLUSTER_NAME}"
+echo "ℹ️ Service: ${SERVICE_NAME}"
+
 ## Construct request
 ## --------
 
-CMD="ecs run ${CLUSTER_NAME} ${CLUSTER_NAME} --launchtype FARGATE"
+CMD="ecs run ${CLUSTER_NAME} ${SERVICE_NAME} --launchtype FARGATE"
 
 for key in $ECS_SUBNETS; do
     CMD="$CMD --subnet $key"
@@ -81,16 +95,14 @@ echo
 ## Wait for task to RUNNING
 ## --------
 
-echo "🕐 Waiting for task to start..."
 echo 
-echo "Task details: https://${AWS_DEFAULT_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_DEFAULT_REGION}#/clusters/${CLUSTER_NAME}/tasks/${TASK_ID}/details"
+echo "Task: https://${AWS_DEFAULT_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_DEFAULT_REGION}#/clusters/${CLUSTER_NAME}/tasks/${TASK_ID}/details"
+echo "Cloudwatch logs: https://${AWS_DEFAULT_REGION}.console.aws.amazon.com/cloudwatch/home?region=${AWS_DEFAULT_REGION}#logsV2:log-groups/log-group/${CLUSTER_NAME}/log-events/${TASK_URL_ENCODED}"
+echo "Follow logs: ecs-cli logs -c ${CLUSTER_NAME} --task-id ${TASK_ID}"
 echo 
-echo "See full logs here: https://${AWS_DEFAULT_REGION}.console.aws.amazon.com/cloudwatch/home?region=${AWS_DEFAULT_REGION}#logsV2:log-groups/log-group/${CLUSTER_NAME}/log-events/${TASK_URL_ENCODED}"
-echo
-echo "or run:"
-echo "ecs-cli logs -c ${CLUSTER_NAME} --task-id ${TASK_ID}"
 
 readonly CMD_TASK_STATUS="aws ecs describe-tasks --cluster ${CLUSTER_NAME} --tasks ${TASK_ARN}"
+LAST_TASK_STATUS_RESULT=""
 
 for index in {1..100}
 do
@@ -100,21 +112,25 @@ do
     case "$TASK_STATUS_RESULT" in
 
       "PROVISIONING" | "PENDING" | "ACTIVATING")
-        echo "🕐 Status: ${TASK_STATUS_RESULT}"
+        [ "$TASK_STATUS_RESULT" = "$LAST_TASK_STATUS_RESULT" ] && echo -n "." || printf "\n🕐 Status: ${TASK_STATUS_RESULT}" 
+        LAST_TASK_STATUS_RESULT=$TASK_STATUS_RESULT
         ;;
       "RUNNING")
-        echo "✅ Task Running: showing last 10 lines of logs"
-        ecs-cli logs -c ${CLUSTER_NAME} --task-id ${TASK_ID} --since 1 | tail -n 20
+        printf "\n✅ Task Running: showing last lines of logs"
+        ecs-cli logs -c ${CLUSTER_NAME} --task-id ${TASK_ID} --since 1 | tail -n 50
+        LAST_TASK_STATUS_RESULT=$TASK_STATUS_RESULT
         ;;
       "DEPROVISIONING" | "STOPPING")
-        echo "⚠️ Task ${TASK_STATUS_RESULT}: so works done"
+        [ "$TASK_STATUS_RESULT" = "$LAST_TASK_STATUS_RESULT" ] && echo -n "." || printf "\n⚠️ Task ${TASK_STATUS_RESULT}: so works done"
+        LAST_TASK_STATUS_RESULT=$TASK_STATUS_RESULT
         ;;
       "STOPPED")
-        echo "⚠️ Task ${TASK_STATUS_RESULT}"
+        printf "\n⚠️ Task ${TASK_STATUS_RESULT}"
         break
         ;;
       *)
-        echo "Unknown status ${TASK_STATUS_RESULT}"
+        [ "$TASK_STATUS_RESULT" = "$LAST_TASK_STATUS_RESULT" ] && echo -n "." || printf "\nUnknown status ${TASK_STATUS_RESULT}"
+        LAST_TASK_STATUS_RESULT=$TASK_STATUS_RESULT
         ;;
     esac
 done 
@@ -137,11 +153,10 @@ echo "or run:"
 echo "ecs-cli logs -c ${CLUSTER_NAME} --task-id ${TASK_ID}"
 echo
 
-if [ "$TASK_EXIT_CODE" -eq "0" ]; then
-  echo "✅✅✅ Task ${TASK_ID} finished with success (exit code: 0)"
+if [ "$TASK_EXIT_CODE" = "0" ]; then
+  echo "✅✅✅ Task ${TASK_ID} finished with success"
 else
-  echo "⚠️ Task ${TASK_ID} finished, without exit code 0"
-  echo "- Exit code is <${TASK_EXIT_CODE}>"
+  echo "⚠️ Task ${TASK_ID} finished with exit code ${TASK_EXIT_CODE}"
   echo "- Reason is '${TASK_EXIT_REASON}'"
 fi
 
